### ISSUE TITLE
zipfile.BadZipFile with com.textra

### ISSUE THREAD

**Issue by NoMore201** [appknox/pyaxmlparser#16]
**Python version**: 3.6.3
**OS**: archlinux
**pyaxmlparser version**: 0.3.6

Downloading the application `com.textra` result in the following error
```
>>> from pyaxmlparser import APK
>>> a = APK('./com.textra.apk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nomore/workspace/nogoogle/lib/python3.6/site-packages/pyaxmlparser/core.py", line 10, in __init__
    self.zip_file = get_zip_file(apk)
  File "/home/nomore/workspace/nogoogle/lib/python3.6/site-packages/pyaxmlparser/utils.py", line 29, in get_zip_file
    return ZipFile(resource)
  File "/usr/lib64/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
Apk data should be valid since I can install it on my android phone succesfully. Let me know if I can provide some more debug information.

**Comment by ChillarAnand** [comment]
@NoMore201 Thanks for the report. This issue is fixed in master.

@subho007 Can you make a new release?

**Comment by subho007** [comment]
@NoMore201 a new version is now available in pypi. Please update it 👍
