### ISSUE TITLE
pyaxmlparser broken by Click 7.0

### ISSUE THREAD

**Issue by xi1976github** [appknox/pyaxmlparser#29]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/lib/python3.7/site-packages), Requirement.parse('click==6.7'), {'pyaxmlparser'})

**Comment by subho007** [comment]
The project uses `click==6.7` specifically. Created a new issue to track this: https://github.com/appknox/pyaxmlparser/issues/38
