### ISSUE TITLE
v0.3.14 package misses public.xml

### ISSUE THREAD

**Issue by eighthave** [appknox/pyaxmlparser#35]
On Debian/stretch, I do `pip3 install gplaycli` which installs _pyaxmlparser_ v0.3.14.  Then it fails with this error:

```
    Traceback (most recent call last):
      File "/usr/local/bin/gplaycli", line 7, in <module>
        from gplaycli.gplaycli import main
      File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 37, in <module>
        from pyaxmlparser import APK
      File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/__init__.py", line 3, in <module>
        from pyaxmlparser.core import APK
      File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/core.py", line 9, in <module>
        from pyaxmlparser.axmlprinter import AXMLPrinter
      File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/axmlprinter.py", line 23, in <module>
        from pyaxmlparser.axmlparser import AXMLParser
      File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/axmlparser.py", line 24, in <module>
        from pyaxmlparser.resources import public
      File "/usr/local/lib/python3.5/dist-packages/pyaxmlparser/resources/public.py", line 21, in <module>
        raise Exception("need to copy the sdk/platforms/android-?/data/res/values/public.xml here")
```

**Comment by eighthave** [comment]
Manually copying _public.xml_ from androguard fixes it.

**Comment by subho007** [comment]
Let me fix this @eighthave

**Comment by subho007** [comment]
Fixed in https://github.com/appknox/pyaxmlparser/pull/36 will update it to a patch version

**Comment by cosmosgenius** [comment]
@eighthave 0.3.15 the missing files are added
