### ISSUE TITLE
Infinite loop when analyzing SettingsIntelligence.apk

### ISSUE THREAD

**Issue by Artzert2215** [appknox/pyaxmlparser#80]
When analyzing a certain app it gets in an infinite loop.
Probably related to #78 
Apk file can be provided if needed.
```
artzert@DESKTOP-EED68NC:~/slimmer$ apkinfo d/system/product/priv-app/SettingsIntelligence/SettingsIntelligence.apk
APK: d/system/product/priv-app/SettingsIntelligence/SettingsIntelligence.apk
res1 is not zero!
res0 is not zero!
res0 is not zero!
res1 is not zero!
res1 is not zero!
res0 is not zero!
res0 is not zero!
res0 is not zero!
...
[100's of lines of the same stuff]
...
res0 is not zero!
res0 is not zero!
Traceback (most recent call last):
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/core.py", line 1478, in get_android_resources
    return self.arsc["resources.arsc"]
KeyError: 'resources.arsc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/artzert/.local/bin/apkinfo", line 8, in <module>
    sys.exit(main())
  File "/home/artzert/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/artzert/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/artzert/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/artzert/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/cli.py", line 34, in main
    click.echo('App name: {}'.format(apk.application))
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/core.py", line 2061, in application
    return self.get_app_name()
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/core.py", line 496, in get_app_name
    res_parser = self.get_android_resources()
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/core.py", line 1484, in get_android_resources
    self.arsc["resources.arsc"] = ARSCParser(self.zip.read("resources.arsc"))
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/arscparser.py", line 138, in __init__
    ate = ARSCResTableEntry(self.buff, res_id, pc)
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/arscutil.py", line 534, in __init__
    self.item = ARSCComplex(buff, parent)
  File "/home/artzert/.local/lib/python3.10/site-packages/pyaxmlparser/arscutil.py", line 580, in __init__
    self.items.append((unpack('<I', buff.read(4))[0],
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by pakbaz-dev** [comment]
https://github.com/appknox/pyaxmlparser/pull/87 should fix it.

**Comment by subho007** [comment]
please provie a sample apk file

**Comment by Artzert2215** [comment]
Sadly I no longer have the exact apk file, it was pulled from a lineage os GSI image at the time. I think it is also a google app, so it most likely originates from a pixel device. 
From the most recent NikGapps-stock-arm64-14-20250127-signed package, I found a probable match.
[SettingsIntelligenceGooglePrebuilt.zip](https://github.com/user-attachments/files/20539323/SettingsIntelligenceGooglePrebuilt.zip)
